package com.smarthotel.controller;
import com.smarthotel.dao.*; import com.smarthotel.model.*; import com.smarthotel.service.HotelService; import com.smarthotel.network.HotelApiService;
import javafx.application.Platform; import javafx.collections.FXCollections; import javafx.fxml.FXML; import javafx.fxml.FXMLLoader; import javafx.scene.Scene; import javafx.scene.control.*; import javafx.scene.layout.*; import javafx.stage.*; import java.io.*; import java.nio.file.*; import java.util.*;

public class AdminController implements SessionAware {
 private User user; private final RoomDao rooms=new RoomDao(); private final CustomerDao customers=new CustomerDao(); private final ReservationDao reservations=new ReservationDao(); private final PaymentDao payments=new PaymentDao(); private final ServiceOrderDao serviceOrders=new ServiceOrderDao(); private final ReviewDao reviews=new ReviewDao(); private final HotelService service=new HotelService(); private final com.smarthotel.service.AuthService auth=new com.smarthotel.service.AuthService();
 @FXML private Label adminName,roomsCount,availableCount,occupiedCount,todayCount,resCount,revenueCount,status,roomPhotoStatus,apiStatus,apiQuote;
 @FXML private TextArea apiJson;
 private final HotelApiService apiService=new HotelApiService();
 @FXML private BorderPane rootPane; @FXML private ScrollPane contentScroll; @FXML private TabPane mainTabs; @FXML private VBox roomFormPanel; @FXML private Button addRoomBtn; @FXML private Label roomFormTitle;
 @FXML private TableView<Room> roomTable; @FXML private TableColumn<Room,String> numCol,catCol,statCol; @FXML private TableColumn<Room,Number> priceCol; @FXML private TextField roomNo,price,capacity,facilities,photoPath; @FXML private ComboBox<String> category,roomStatus;
 @FXML private TableView<Customer> customerTable; @FXML private TableColumn<Customer,String> customerNameCol,customerEmailCol,customerPhoneCol; @FXML private TextField customerSearch,customerName,customerEmail,customerPhone,customerAddress,customerUsername; @FXML private PasswordField customerPassword; @FXML private TextArea customerHistory;
 @FXML private TableView<Reservation> reservationTable; @FXML private TableColumn<Reservation,Number> reservationIdCol,reservationTotalCol,reservationGuestsCol; @FXML private TableColumn<Reservation,String> reservationCustomerCol,reservationRoomCol,reservationDateCol,reservationStatusCol; @FXML private TextField reservationSearch; @FXML private DatePicker reservationIn,reservationOut; @FXML private Spinner<Integer> reservationGuests;
 @FXML private TableView<Payment> paymentTable; @FXML private TableColumn<Payment,Number> paymentIdCol,paymentAmountCol; @FXML private TableColumn<Payment,String> paymentMethodCol,paymentStatusCol,paymentReservationCol; @FXML private TextField paymentReservationId,paymentAmount; @FXML private ComboBox<String> paymentMethod,paymentStatus;
 @FXML private TableView<ServiceOrder> serviceRequestTable; @FXML private TableColumn<ServiceOrder,Number> serviceRequestIdCol,serviceRequestReservationCol,serviceRequestQtyCol,serviceRequestAmountCol; @FXML private TableColumn<ServiceOrder,String> serviceRequestNameCol,serviceRequestStatusCol,serviceRequestMessageCol; @FXML private ComboBox<String> serviceDecision; @FXML private TextField serviceMessage;
 @FXML private TableView<Review> reviewTable; @FXML private TableColumn<Review,Number> reviewIdCol,reviewRatingCol,reviewCustomerCol,reviewReservationCol; @FXML private TableColumn<Review,String> reviewCommentCol,reviewDateCol;

 @Override public void setUser(User u){user=u;if(adminName!=null)adminName.setText(u==null?"Administrator":"Administrator · "+u.username());}
 @FXML public void initialize(){
  // Explicit responsive bindings for the main dashboard.
  if(rootPane!=null){ rootPane.sceneProperty().addListener((obs,oldScene,newScene)->{ if(newScene!=null){ rootPane.prefWidthProperty().bind(newScene.widthProperty()); rootPane.prefHeightProperty().bind(newScene.heightProperty()); } }); }
  roomTable.getSelectionModel().selectedItemProperty().addListener((o,a,b)->selectRoom());customerTable.getSelectionModel().selectedItemProperty().addListener((o,a,b)->selectCustomer());reservationTable.getSelectionModel().selectedItemProperty().addListener((o,a,b)->selectReservation());paymentTable.getSelectionModel().selectedItemProperty().addListener((o,a,b)->selectPayment());serviceRequestTable.getSelectionModel().selectedItemProperty().addListener((o,a,b)->selectServiceRequest());
  numCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().roomNumber()));catCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().category()));priceCol.setCellValueFactory(c->new javafx.beans.property.SimpleDoubleProperty(c.getValue().price()));statCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().status()));
  customerNameCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().fullName()));customerEmailCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().email()));customerPhoneCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().phone()==null?"":c.getValue().phone()));
  reservationIdCol.setCellValueFactory(c->new javafx.beans.property.SimpleIntegerProperty(c.getValue().id()));reservationCustomerCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(customerName(c.getValue().customerId())));reservationRoomCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(roomNumber(c.getValue().roomId())));reservationDateCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().checkIn()+" → "+c.getValue().checkOut()));reservationGuestsCol.setCellValueFactory(c->new javafx.beans.property.SimpleIntegerProperty(c.getValue().guests()));reservationTotalCol.setCellValueFactory(c->new javafx.beans.property.SimpleDoubleProperty(c.getValue().total()));reservationStatusCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().status()));
  paymentIdCol.setCellValueFactory(c->new javafx.beans.property.SimpleIntegerProperty(c.getValue().id()));paymentReservationCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(String.valueOf(c.getValue().reservationId())));paymentAmountCol.setCellValueFactory(c->new javafx.beans.property.SimpleDoubleProperty(c.getValue().amount()));paymentMethodCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().method()));paymentStatusCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().status()));
  serviceRequestIdCol.setCellValueFactory(c->new javafx.beans.property.SimpleIntegerProperty(c.getValue().id()));serviceRequestReservationCol.setCellValueFactory(c->new javafx.beans.property.SimpleIntegerProperty(c.getValue().reservationId()));serviceRequestNameCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().serviceName()));serviceRequestQtyCol.setCellValueFactory(c->new javafx.beans.property.SimpleIntegerProperty(c.getValue().quantity()));serviceRequestAmountCol.setCellValueFactory(c->new javafx.beans.property.SimpleDoubleProperty(c.getValue().amount()));serviceRequestStatusCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().status()));serviceRequestMessageCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().message()==null?"":c.getValue().message()));
  reviewIdCol.setCellValueFactory(c->new javafx.beans.property.SimpleIntegerProperty(c.getValue().id()));reviewRatingCol.setCellValueFactory(c->new javafx.beans.property.SimpleIntegerProperty(c.getValue().rating()));reviewCustomerCol.setCellValueFactory(c->new javafx.beans.property.SimpleIntegerProperty(c.getValue().customerId()));reviewReservationCol.setCellValueFactory(c->new javafx.beans.property.SimpleIntegerProperty(c.getValue().reservationId()));reviewCommentCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().comment()==null?"":c.getValue().comment()));reviewDateCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().createdAt()));
  category.setItems(FXCollections.observableArrayList("Single","Double","Deluxe","Suite"));roomStatus.setItems(FXCollections.observableArrayList("AVAILABLE","RESERVED","OCCUPIED","MAINTENANCE"));reservationGuests.setValueFactory(new SpinnerValueFactory.IntegerSpinnerValueFactory(1,8,1));paymentMethod.setItems(FXCollections.observableArrayList("Cash","Card","Online"));paymentStatus.setItems(FXCollections.observableArrayList("PAID","PENDING","REFUNDED","FAILED"));paymentStatus.setValue("PAID");serviceDecision.setItems(FXCollections.observableArrayList("APPROVED","REJECTED","PENDING"));serviceDecision.setValue("APPROVED");load();
 }
 private String customerName(int id){try{Customer c=customers.byId(id);return c==null?"#"+id:c.fullName();}catch(Exception e){return "#"+id;}} private String roomNumber(int id){try{Room r=rooms.byId(id);return r==null?"#"+id:r.roomNumber();}catch(Exception e){return "#"+id;}}
 private void load(){try{var rs=rooms.allForAdmin();var cs=customers.all();var bs=reservations.all();var ps=payments.all();var sos=serviceOrders.all();var rev=reviews.all();var st=service.stats();roomTable.setItems(FXCollections.observableArrayList(rs));customerTable.setItems(FXCollections.observableArrayList(cs));reservationTable.setItems(FXCollections.observableArrayList(bs));paymentTable.setItems(FXCollections.observableArrayList(ps));serviceRequestTable.setItems(FXCollections.observableArrayList(sos));reviewTable.setItems(FXCollections.observableArrayList(rev));roomsCount.setText(String.valueOf(st.get("rooms")));availableCount.setText(String.valueOf(st.get("available")));occupiedCount.setText(String.valueOf(st.get("occupied")));todayCount.setText(st.get("checkins")+" / "+st.get("checkouts"));resCount.setText(String.valueOf(st.get("reservations")));revenueCount.setText("$"+st.get("revenue"));}catch(Exception e){show("Dashboard load failed: "+msg(e));}}
 @FXML private void toggleRoomForm(){boolean v=!roomFormPanel.isVisible();roomFormPanel.setVisible(v);roomFormPanel.setManaged(v);if(v){roomTable.getSelectionModel().clearSelection();clearRoomFields();roomFormTitle.setText("Add New Room");addRoomBtn.setText("✕ Close");}else addRoomBtn.setText("+ Add Room");}
 @FXML private void cancelRoomForm(){roomFormPanel.setVisible(false);roomFormPanel.setManaged(false);addRoomBtn.setText("+ Add Room");clearRoomFields();roomTable.getSelectionModel().clearSelection();}
 @FXML private void choosePhoto(){FileChooser fc=new FileChooser();fc.setTitle("Choose Room Photo");fc.getExtensionFilters().add(new FileChooser.ExtensionFilter("Images","*.png","*.jpg","*.jpeg","*.webp"));File f=fc.showOpenDialog(roomTable.getScene().getWindow());if(f==null)return;try{Path dir=Paths.get("room_images");Files.createDirectories(dir);String ext=f.getName().contains(".")?f.getName().substring(f.getName().lastIndexOf('.')):".jpg";String name="room_"+System.currentTimeMillis()+ext;Path dest=dir.resolve(name);Files.copy(f.toPath(),dest,StandardCopyOption.REPLACE_EXISTING);photoPath.setText(dest.toAbsolutePath().toString());roomPhotoStatus.setText("Photo selected: "+f.getName());}catch(Exception e){roomPhotoStatus.setText("Photo error: "+msg(e));}}
 @FXML private void saveRoom(){try{Room x=roomTable.getSelectionModel().getSelectedItem();int id=x==null?0:x.id();String no=roomNo.getText().trim(),cat=category.getValue();if(no.isBlank()||cat==null)throw new IllegalArgumentException("Room number and category are required.");double pr=Double.parseDouble(price.getText().trim());int cap=Integer.parseInt(capacity.getText().trim());rooms.save(new Room(id,no,cat,pr,cap,facilities.getText().trim(),"Room managed by admin",roomStatus.getValue()==null?"AVAILABLE":roomStatus.getValue(),photoPath.getText().trim()));cancelRoomForm();load();show("Room saved successfully.");}catch(Exception e){show("Room error: "+msg(e));}}
 @FXML private void deleteRoom(){try{Room x=roomTable.getSelectionModel().getSelectedItem();if(x==null)throw new IllegalArgumentException("Select a room first.");rooms.delete(x.id());cancelRoomForm();load();show("Room deleted.");}catch(Exception e){show("Cannot delete room: "+msg(e));}}
 private void selectRoom(){Room x=roomTable.getSelectionModel().getSelectedItem();if(x!=null){roomNo.setText(x.roomNumber());category.setValue(x.category());price.setText(String.valueOf(x.price()));capacity.setText(String.valueOf(x.capacity()));facilities.setText(x.facilities()==null?"":x.facilities());roomStatus.setValue(x.status());photoPath.setText(x.photoPath()==null?"":x.photoPath());roomPhotoStatus.setText(x.photoPath()==null||x.photoPath().isBlank()?"No photo uploaded":"Photo uploaded");roomFormTitle.setText("Edit Room · "+x.roomNumber());roomFormPanel.setVisible(true);roomFormPanel.setManaged(true);addRoomBtn.setText("✕ Close");}}
 private void clearRoomFields(){roomNo.clear();price.clear();capacity.clear();facilities.clear();category.setValue(null);roomStatus.setValue(null);photoPath.clear();roomPhotoStatus.setText("No photo selected");}
 @FXML private void searchCustomers(){try{customerTable.setItems(FXCollections.observableArrayList(customers.search(customerSearch.getText())));}catch(Exception e){show(msg(e));}}
 @FXML private void addCustomer(){try{String n=customerName.getText().trim(),em=customerEmail.getText().trim(),u=customerUsername.getText().trim(),pw=customerPassword.getText();if(n.isBlank()||em.isBlank()||u.isBlank()||pw.length()<6)throw new IllegalArgumentException("Name, email, username and 6+ character password are required.");int uid=auth.register(u,pw,"CUSTOMER");customers.create(uid,n,em,customerPhone.getText().trim(),customerAddress.getText().trim());load();show("Customer account created.");}catch(Exception e){show("Add customer failed: "+msg(e));}}
 @FXML private void saveCustomer(){try{Customer c=customerTable.getSelectionModel().getSelectedItem();if(c==null)throw new IllegalArgumentException("Select a customer.");customers.update(c.id(),customerName.getText().trim(),customerEmail.getText().trim(),customerPhone.getText().trim(),customerAddress.getText().trim());load();show("Customer updated.");}catch(Exception e){show("Customer error: "+msg(e));}}
 @FXML private void deleteCustomer(){try{Customer c=customerTable.getSelectionModel().getSelectedItem();if(c==null)throw new IllegalArgumentException("Select a customer.");customers.delete(c.id());load();show("Customer deleted.");}catch(Exception e){show("Cannot delete customer: "+msg(e));}}
 private void selectCustomer(){Customer c=customerTable.getSelectionModel().getSelectedItem();if(c==null)return;customerName.setText(c.fullName());customerEmail.setText(c.email());customerPhone.setText(c.phone()==null?"":c.phone());customerAddress.setText(c.address()==null?"":c.address());try{StringBuilder b=new StringBuilder();for(Reservation r:reservations.byCustomer(c.id()))b.append("Booking #").append(r.id()).append(" | ").append(r.checkIn()).append(" → ").append(r.checkOut()).append(" | ").append(r.status()).append(" | $").append(r.total()).append('\n');customerHistory.setText(b.length()==0?"No booking history.":b.toString());}catch(Exception e){customerHistory.setText("Unable to load history.");}}
 @FXML private void searchReservations(){try{reservationTable.setItems(FXCollections.observableArrayList(reservations.search(reservationSearch.getText())));}catch(Exception e){show(msg(e));}}
 private void selectReservation(){Reservation r=reservationTable.getSelectionModel().getSelectedItem();if(r==null)return;reservationIn.setValue(java.time.LocalDate.parse(r.checkIn()));reservationOut.setValue(java.time.LocalDate.parse(r.checkOut()));reservationGuests.getValueFactory().setValue(r.guests());paymentReservationId.setText(String.valueOf(r.id()));paymentAmount.setText(String.valueOf(r.total()));}
 @FXML private void confirmReservation(){changeReservationStatus("CONFIRMED");}@FXML private void cancelReservation(){try{Reservation r=selectedReservation();reservations.cancel(r.id());load();show("Reservation cancelled.");}catch(Exception e){show("Cancel failed: "+msg(e));}}
 @FXML private void checkIn(){try{Reservation r=selectedReservation();reservations.checkIn(r.id());load();show("Customer checked in.");}catch(Exception e){show("Check-in failed: "+msg(e));}}
 @FXML private void checkOut(){try{Reservation r=selectedReservation();reservations.checkOut(r.id());load();show("Customer checked out. Final bill: $"+r.total());}catch(Exception e){show("Check-out failed: "+msg(e));}}
 private void changeReservationStatus(String s){try{Reservation r=selectedReservation();reservations.setStatus(r.id(),s);load();show("Reservation marked "+s+".");}catch(Exception e){show("Update failed: "+msg(e));}}
 @FXML private void modifyReservation(){try{Reservation r=selectedReservation();Room room=rooms.byId(r.roomId());long nights=reservations.nights(reservationIn.getValue().toString(),reservationOut.getValue().toString());double total=room.price()*nights;reservations.modify(r.id(),reservationIn.getValue().toString(),reservationOut.getValue().toString(),reservationGuests.getValue(),total);load();show("Reservation modified. New bill: $"+total);}catch(Exception e){show("Modify failed: "+msg(e));}}
 private Reservation selectedReservation(){Reservation r=reservationTable.getSelectionModel().getSelectedItem();if(r==null)throw new IllegalArgumentException("Select a reservation first.");return r;}
 private void selectPayment(){Payment p=paymentTable.getSelectionModel().getSelectedItem();if(p==null)return;paymentReservationId.setText(String.valueOf(p.reservationId()));paymentAmount.setText(String.valueOf(p.amount()));paymentMethod.setValue(p.method());paymentStatus.setValue(p.status());}
 @FXML private void recordPayment(){try{int rid=Integer.parseInt(paymentReservationId.getText().trim());double amount=Double.parseDouble(paymentAmount.getText().trim());if(paymentMethod.getValue()==null)throw new IllegalArgumentException("Select payment method.");payments.create(rid,amount,paymentMethod.getValue(),"ADMIN-"+System.currentTimeMillis());load();show("Payment created.");}catch(Exception e){show("Payment error: "+msg(e));}}
 @FXML private void updatePayment(){try{Payment p=paymentTable.getSelectionModel().getSelectedItem();if(p==null)throw new IllegalArgumentException("Select a payment.");payments.update(p.id(),Integer.parseInt(paymentReservationId.getText().trim()),Double.parseDouble(paymentAmount.getText().trim()),paymentMethod.getValue(),paymentStatus.getValue(),p.reference());load();show("Payment updated.");}catch(Exception e){show("Payment update failed: "+msg(e));}}
 @FXML private void deletePayment(){try{Payment p=paymentTable.getSelectionModel().getSelectedItem();if(p==null)throw new IllegalArgumentException("Select a payment.");payments.delete(p.id());load();show("Payment deleted.");}catch(Exception e){show("Payment delete failed: "+msg(e));}}
 private void selectServiceRequest(){ServiceOrder x=serviceRequestTable.getSelectionModel().getSelectedItem();if(x==null)return;serviceDecision.setValue(x.status());serviceMessage.setText(x.message()==null?"":x.message());}
 @FXML private void decideService(){try{ServiceOrder x=serviceRequestTable.getSelectionModel().getSelectedItem();if(x==null)throw new IllegalArgumentException("Select a service request.");String decision=serviceDecision.getValue();String message=serviceMessage.getText().trim();if(message.isBlank())message="Service request "+decision.toLowerCase()+" by admin.";serviceOrders.setDecision(x.id(),decision,message);if("APPROVED".equals(decision))reservations.recalculateTotal(x.reservationId());load();show("Service request updated and customer message saved.");}catch(Exception e){show("Service decision failed: "+msg(e));}}
 @FXML private void testApi(){
  apiStatus.setText("Fetching JSON in background thread...");
  apiQuote.setText("Parsed quote: —");
  apiJson.setText("Waiting for HTTP response...");
  apiService.fetchTip().thenAccept(json -> Platform.runLater(() -> {
    try { apiJson.setText(json); apiQuote.setText("Parsed quote: " + apiService.parseQuote(json)); apiStatus.setText("HTTP GET + Jackson JSON parsing completed successfully."); }
    catch(Exception e){ apiStatus.setText("JSON parsing failed: "+msg(e)); }
  }));
 }
 @FXML private void refresh(){load();show("Dashboard refreshed.");}
 @FXML private void logout()throws Exception{Stage stage=(Stage)adminName.getScene().getWindow();FXMLLoader l=new FXMLLoader(getClass().getResource("/fxml/login.fxml"));Scene sc=new Scene(l.load(),1200,760);var css=getClass().getResource("/css/app.css");if(css!=null)sc.getStylesheets().add(css.toExternalForm());stage.setScene(sc);stage.setTitle("Smart Hotel | Login");stage.centerOnScreen();}
 private void show(String s){if(status!=null)status.setText(s);}private String msg(Exception e){return e.getMessage()==null?"Unknown error.":e.getMessage();}
}
