package com.smarthotel.controller;
import com.smarthotel.dao.*;
import com.smarthotel.model.*;
import com.smarthotel.service.HotelService;
import javafx.application.Platform; import javafx.collections.FXCollections; import javafx.fxml.FXML; import javafx.fxml.FXMLLoader; import javafx.scene.Scene; import javafx.scene.control.*; import javafx.scene.image.Image; import javafx.scene.image.ImageView; import javafx.scene.layout.VBox; import javafx.stage.Stage;
import java.io.File; import java.time.LocalDate; import java.util.List;

public class CustomerController implements SessionAware {
 private User user; private Customer customer;
 private final RoomDao rooms=new RoomDao(); private final CustomerDao customers=new CustomerDao(); private final PaymentDao payments=new PaymentDao(); private final ServiceDao serviceDao=new ServiceDao(); private final ServiceOrderDao serviceOrders=new ServiceOrderDao(); private final ReviewDao reviews=new ReviewDao(); private final HotelService service=new HotelService();
 @FXML private Label welcome,quote,status,profileEmail,profilePhone,profileAddress,nightlyPrice,stayTotal;
 @FXML private javafx.scene.layout.BorderPane rootPane;
 @FXML private TableView<Room> roomTable; @FXML private TableColumn<Room,String> numCol,catCol,statCol,facilitiesCol; @FXML private TableColumn<Room,Number> priceCol,capacityCol;
 @FXML private DatePicker checkIn,checkOut; @FXML private Spinner<Integer> guests; @FXML private ComboBox<String> roomType,paymentMethod; 
 @FXML private TableView<Reservation> bookings; @FXML private TableColumn<Reservation,Number> bidCol,totalCol,guestsCol; @FXML private TableColumn<Reservation,String> bstatusCol,inCol,outCol,paymentStatusCol;
 @FXML private ComboBox<ServiceItem> serviceChoice; @FXML private Spinner<Integer> serviceQty; @FXML private TableView<ServiceOrder> serviceTable; @FXML private TableColumn<ServiceOrder,String> serviceNameCol,serviceStatusCol,serviceMessageCol; @FXML private TableColumn<ServiceOrder,Number> serviceQtyCol,serviceAmountCol;
 @FXML private ComboBox<Integer> ratingChoice; @FXML private TextArea reviewComment; @FXML private TextField editName,editEmail,editPhone,editAddress;

 @Override public void setUser(User u){user=u;try{customer=customers.byUser(u.id());refresh();loadProfile();loadServices();}catch(Exception e){if(status!=null)status.setText("Unable to load customer profile: "+e.getMessage());}}
 @FXML public void initialize(){
  if(rootPane!=null){ rootPane.sceneProperty().addListener((obs,oldScene,newScene)->{ if(newScene!=null){ rootPane.prefWidthProperty().bind(newScene.widthProperty()); rootPane.prefHeightProperty().bind(newScene.heightProperty()); } }); }
  numCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().roomNumber()));catCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().category()));priceCol.setCellValueFactory(c->new javafx.beans.property.SimpleDoubleProperty(c.getValue().price()));capacityCol.setCellValueFactory(c->new javafx.beans.property.SimpleIntegerProperty(c.getValue().capacity()));facilitiesCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().facilities()==null?"":c.getValue().facilities()));statCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().status()));
  roomType.setItems(FXCollections.observableArrayList("All","Single","Double","Deluxe","Suite"));roomType.setValue("All");paymentMethod.setItems(FXCollections.observableArrayList("Cash","Card","Online"));guests.setValueFactory(new SpinnerValueFactory.IntegerSpinnerValueFactory(1,8,1));
  bidCol.setCellValueFactory(c->new javafx.beans.property.SimpleIntegerProperty(c.getValue().id()));inCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().checkIn()));outCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().checkOut()));guestsCol.setCellValueFactory(c->new javafx.beans.property.SimpleIntegerProperty(c.getValue().guests()));totalCol.setCellValueFactory(c->new javafx.beans.property.SimpleDoubleProperty(c.getValue().total()));bstatusCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().status()));paymentStatusCol.setCellValueFactory(c->{try{return new javafx.beans.property.SimpleStringProperty(payments.statusForReservation(c.getValue().id()));}catch(Exception e){return new javafx.beans.property.SimpleStringProperty("UNPAID");}});
  serviceNameCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().serviceName()));serviceQtyCol.setCellValueFactory(c->new javafx.beans.property.SimpleIntegerProperty(c.getValue().quantity()));serviceAmountCol.setCellValueFactory(c->new javafx.beans.property.SimpleDoubleProperty(c.getValue().amount()));serviceStatusCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().status()));serviceMessageCol.setCellValueFactory(c->new javafx.beans.property.SimpleStringProperty(c.getValue().message()==null?"":c.getValue().message()));
  ratingChoice.setItems(FXCollections.observableArrayList(1,2,3,4,5));ratingChoice.setValue(5);serviceQty.setValueFactory(new SpinnerValueFactory.IntegerSpinnerValueFactory(1,10,1));
  roomTable.getSelectionModel().selectedItemProperty().addListener((o,a,b)->updatePrice());bookings.getSelectionModel().selectedItemProperty().addListener((o,a,b)->loadSelectedServices());
  roomTable.setRowFactory(tv->{TableRow<Room> row=new TableRow<>();row.setOnMouseClicked(e->{if(!row.isEmpty()&&e.getClickCount()==2)showRoom(row.getItem());});return row;});
 }
 private void loadServices(){try{serviceChoice.setItems(FXCollections.observableArrayList(serviceDao.active()));serviceChoice.setConverter(new javafx.util.StringConverter<>(){public String toString(ServiceItem x){return x==null?"":x.name()+" — $"+x.price();}public ServiceItem fromString(String s){return null;}});}catch(Exception e){status.setText("Could not load services: "+e.getMessage());}}
 @FXML private void searchRooms(){try{String in=checkIn.getValue()==null?null:checkIn.getValue().toString(),out=checkOut.getValue()==null?null:checkOut.getValue().toString();roomTable.setItems(FXCollections.observableArrayList(rooms.find(roomType.getValue(),in,out,guests.getValue())));status.setText(roomTable.getItems().size()+" available room(s) found. Double-click a room to view its photo/details.");updatePrice();}catch(Exception e){status.setText("Room search failed: "+e.getMessage());}}
 @FXML private void viewRoom(){Room r=roomTable.getSelectionModel().getSelectedItem();if(r==null){status.setText("Select a room first.");return;}showRoom(r);}
 private void showRoom(Room r){Stage d=new Stage();d.setTitle("Room "+r.roomNumber()+" — "+r.category());VBox box=new VBox(10);box.setStyle("-fx-padding:18;-fx-background-color:white;");ImageView iv=new ImageView();iv.setFitWidth(520);iv.setFitHeight(300);iv.setPreserveRatio(true);if(r.photoPath()!=null&&!r.photoPath().isBlank()&&new File(r.photoPath()).exists())iv.setImage(new Image(new File(r.photoPath()).toURI().toString()));else {Label no=new Label("No room photo has been uploaded by admin.");no.setStyle("-fx-font-size:16px;");box.getChildren().add(no);}box.getChildren().addAll(iv,new Label("Room "+r.roomNumber()+" • "+r.category()),new Label("$"+r.price()+" per night • Capacity: "+r.capacity()),new Label("Facilities: "+(r.facilities()==null?"":r.facilities())),new Label(r.description()==null?"":r.description()),new Button("Close"));((Button)box.getChildren().get(box.getChildren().size()-1)).setOnAction(e->d.close());d.setScene(new Scene(box,600,430));d.show();}
 private void updatePrice(){Room r=roomTable==null?null:roomTable.getSelectionModel().getSelectedItem();if(r==null){nightlyPrice.setText("Room: —");stayTotal.setText("Total: —");return;}nightlyPrice.setText(String.format("Room: $%.2f / night",r.price()));if(checkIn.getValue()!=null&&checkOut.getValue()!=null&&checkIn.getValue().isBefore(checkOut.getValue())){long n=java.time.temporal.ChronoUnit.DAYS.between(checkIn.getValue(),checkOut.getValue());stayTotal.setText(String.format("Total room cost: $%.2f (%d night%s)",r.price()*n,n,n==1?"":"s"));}else stayTotal.setText("Total: choose check-in and check-out.");}
 @FXML private void book(){try{Room r=roomTable.getSelectionModel().getSelectedItem();if(r==null)throw new IllegalArgumentException("Select a room.");if(customer==null)throw new IllegalArgumentException("Customer profile not loaded.");if(checkIn.getValue()==null||checkOut.getValue()==null)throw new IllegalArgumentException("Select check-in and check-out.");if(!checkIn.getValue().isBefore(checkOut.getValue()))throw new IllegalArgumentException("Check-out must be after check-in.");if(paymentMethod.getValue()==null)throw new IllegalArgumentException("Select a payment method.");service.book(customer,r,checkIn.getValue(),checkOut.getValue(),guests.getValue(),paymentMethod.getValue());refresh();status.setText("Booking confirmed. You can request extra services below.");}catch(Exception e){status.setText("Booking failed: "+e.getMessage());}}
 @FXML private void requestService(){try{Reservation r=selectedBooking();ServiceItem s=serviceChoice.getValue();if(s==null)throw new IllegalArgumentException("Choose a service.");serviceOrders.request(r.id(),s.id(),serviceQty.getValue());loadSelectedServices();status.setText(s.name()+" requested. Waiting for admin approval.");}catch(Exception e){status.setText("Service request failed: "+e.getMessage());}}
 private void loadSelectedServices(){Reservation r=bookings.getSelectionModel().getSelectedItem();if(r==null){serviceTable.getItems().clear();return;}try{serviceTable.setItems(FXCollections.observableArrayList(serviceOrders.byReservation(r.id())));}catch(Exception e){status.setText("Could not load services: "+e.getMessage());}}
 @FXML private void rateBooking(){try{Reservation r=selectedBooking();if(reviews.byReservation(r.id())!=null)throw new IllegalArgumentException("This booking already has a rating.");reviews.save(customer.id(),r.id(),ratingChoice.getValue(),reviewComment.getText().trim());reviewComment.clear();status.setText("Thank you. Your rating has been submitted to admin.");}catch(Exception e){status.setText("Rating failed: "+e.getMessage());}}
 private Reservation selectedBooking(){Reservation r=bookings.getSelectionModel().getSelectedItem();if(r==null)throw new IllegalArgumentException("Select a booking first.");return r;}
 @FXML private void refresh(){try{if(customer!=null)bookings.setItems(FXCollections.observableArrayList(service.reservations.byCustomer(customer.id())));loadSelectedServices();}catch(Exception e){status.setText(e.getMessage());}}
 private void loadProfile(){if(customer==null)return;welcome.setText("Welcome, "+customer.fullName());profileEmail.setText(customer.email());profilePhone.setText(customer.phone()==null||customer.phone().isBlank()?"No phone added":customer.phone());profileAddress.setText(customer.address()==null||customer.address().isBlank()?"No address added":customer.address());editName.setText(customer.fullName());editEmail.setText(customer.email());editPhone.setText(customer.phone()==null?"":customer.phone());editAddress.setText(customer.address()==null?"":customer.address());}
 @FXML private void updateProfile(){try{customers.update(customer.id(),editName.getText().trim(),editEmail.getText().trim(),editPhone.getText().trim(),editAddress.getText().trim());customer=customers.byId(customer.id());loadProfile();status.setText("Profile updated successfully.");}catch(Exception e){status.setText("Profile update failed: "+e.getMessage());}}
 @FXML private void logout()throws Exception{Stage stage=(Stage)welcome.getScene().getWindow();FXMLLoader l=new FXMLLoader(getClass().getResource("/fxml/login.fxml"));Scene sc=new Scene(l.load(),1200,760);var css=getClass().getResource("/css/app.css");if(css!=null)sc.getStylesheets().add(css.toExternalForm());stage.setScene(sc);stage.setTitle("Smart Hotel | Login");stage.centerOnScreen();}
}
